version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: tikur_abay
    volumes:
      - mongo_data:/data/db

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: tikurabay
      MINIO_ROOT_PASSWORD: tikurabay123
    volumes:
      - minio_data:/data

volumes:
  mongo_data:
  minio_data:
