import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'services/driver_api.dart';

enum DriverLanguage { en, am }

final ValueNotifier<DriverLanguage> driverLanguageNotifier =
    ValueNotifier(DriverLanguage.en);

const _languageStorageKey = 'tikur_abay_driver_language';

const Map<DriverLanguage, Map<String, String>> _dictionary = {
  DriverLanguage.en: {
    'appTitle': 'Tikur Abay Mobile',
    'customerHomeTitle': 'Customer Home',
    'driverHomeTitle': 'Driver Home',
    'trip': 'Trips',
    'report': 'Reports',
    'activity': 'Activity',
    'chat': 'Chat',
    'docs': 'Docs',
    'alerts': 'Alerts',
    'profile': 'Profile',
    'home': 'Home',
    'availability': 'Availability',
    'quotes': 'Quotes',
    'payments': 'Payments',
    'notifications': 'Notifications',
    'phoneOrEmail': 'Phone or Email',
    'password': 'Password',
    'language': 'Language',
    'languageEnglish': 'English',
    'languageAmharic': 'Amharic',
    'signIn': 'Sign in',
    'enterDriverConsole': 'Open workspace',
    'signingIn': 'Signing In...',
    'driverLoginIntro':
        'Access trips, field reporting, documents, and dispatch chat from one mobile workspace.',
    'mobileIntro':
        'Customer and driver operations in one secure mobile workspace.',
    'register': 'Register',
    'createAccount': 'Create account',
    'creatingAccount': 'Creating account...',
    'fullName': 'Full name',
    'phoneNumber': 'Phone number',
    'email': 'Email',
    'roleSelection': 'Choose your role',
    'customerBusinessUser': 'Customer / Business User',
    'driverRole': 'Driver',
    'welcomeTikurAbay': 'Welcome to Tikur Abay',
    'welcomeMobileSubtitle':
        'Smart transport access for customers and drivers.',
    'continueAs': 'Continue as',
    'customerUserShort': 'Customer / User',
    'customerRoleSubtitle':
        'Phone or email first, then OTP and quick profile setup if new.',
    'driverRoleSubtitle':
        'Use your phone number and 4-digit PIN for simple driver access.',
    'chooseHowContinue':
        'Choose how you want to continue. Drivers stay in onboarding status until KYC is approved.',
    'customerLoginTitle': 'Customer Login',
    'customerLoginSubtitle':
        'Use your phone number or email first. We will send a one-time verification code.',
    'driverLoginTitle': 'Driver Login',
    'driverLoginSubtitle':
        'Sign in with your phone number and 4-digit PIN. KYC approval still controls trip access.',
    'useEmailInstead': 'Use email instead',
    'phoneDefaultSignIn': 'Phone remains the default sign-in method.',
    'sendOtp': 'Send OTP',
    'sendingCode': 'Sending code...',
    'phoneFirstAccess': 'Phone-first access',
    'verifyCode': 'Verify code',
    'verifyingCode': 'Verifying...',
    'resendCode': 'Resend code',
    'resendingCode': 'Resending...',
    'changeNumber': 'Change number',
    'otpCode': 'OTP code',
    'enterSixDigits': 'Enter 6 digits',
    'otpTitle': 'Enter Verification Code',
    'driverType': 'Driver type',
    'internalDriver': 'Internal driver',
    'externalDriver': 'External partner driver',
    'companyName': 'Company name',
    'tradeLicense': 'Trade license',
    'tin': 'TIN',
    'vat': 'VAT',
    'address': 'Address',
    'faydaFront': 'Fayda front document ID',
    'faydaBack': 'Fayda back document ID',
    'selfieDocument': 'Selfie document ID',
    'driverLicense': 'Driver license',
    'branchId': 'Branch ID',
    'partnerCompany': 'Partner company',
    'partnerVehicleCode': 'Partner vehicle / mapping code',
    'emergencyContactName': 'Emergency contact',
    'driverKycRequired': 'Driver KYC required',
    'driverKycHelp':
        'Submit Fayda front and back, phone, and license details. Driver actions unlock after HR or operations approval.',
    'driverKycLifecycle': 'KYC lifecycle',
    'driverKycLifecycleValue':
        'draft → submitted → under review → approved / rejected / suspended',
    'submitQuote': 'Request quote',
    'sendBooking': 'Send booking',
    'availabilityAndQuotes': 'Availability & Quotes',
    'openWorkspace': 'Open workspace',
    'forgotPassword': 'Forgot password',
    'support': 'Support',
    'customer': 'Customer',
    'customerTrips': 'Trips',
    'customerDocs': 'Docs',
    'myQuotes': 'Quotes',
    'myTrips': 'Trips',
    'driverTrips': 'Trips',
    'reportCenter': 'Reports',
    'documentCenter': 'Docs',
    'managerConsole': 'Manager Console',
    'pendingApproval': 'Pending approval',
    'trackShipment': 'Track shipment',
    'quoteStatus': 'Quote status',
    'agreement': 'Agreement',
    'activeTrips': 'Active trips',
    'invoicesDue': 'Invoices due',
    'currentBooking': 'Current booking',
    'tripProgress': 'Trip progress',
    'supportShortcut': 'Support shortcut',
    'tripDetail': 'Trip detail',
    'milestones': 'Milestones',
    'currentStatus': 'Current status',
    'latestCheckpoint': 'Latest checkpoint',
    'assignedVehicle': 'Assigned vehicle',
    'podStatus': 'POD status',
    'viewDetail': 'View detail',
    'noTripsYet':
        'No trips are active yet. Once a booking is assigned, trip milestones and ETA will appear here.',
    'noQuotesAvailable': 'No quotes are available right now.',
    'reportOverview': 'Report center',
    'reportOverviewSubtitle':
        'Fuel, incidents, delays, maintenance, and workflow updates in one operational queue.',
    'recentSubmissions': 'Recent submissions',
    'noReportsYet': 'No reports have been submitted yet.',
    'nextAction': 'Next action',
    'fieldPackage':
        'Trip, vehicle, driver, GPS, odometer, urgency, and attachments',
    'fuelAndReceipts': 'Fuel, receipt, station, and odometer',
    'reportSubmittedSuccessfully': 'Submission recorded successfully.',
    'descriptionRequired': 'Description is required.',
    'odometerKm': 'Odometer KM',
    'liters': 'Liters',
    'cost': 'Cost',
    'urgencyLabel': 'Urgency',
    'notes': 'Notes',
    'descriptionLabel': 'Description',
    'receiptAttachment': 'Receipt / attachment',
    'photoAttachment': 'Photo attachment',
    'pick': 'Pick',
    'submit': 'Submit',
    'submitting': 'Submitting...',
    'tripUnavailable': 'Trip details unavailable.',
    'timeline': 'Timeline',
    'documents': 'Documents',
    'paymentLink': 'Payment link',
    'routeStatus': 'Route status',
    'customerWorkspace': 'Customer workspace',
    'assignedTripsAndDeliveryMilestones':
        'Assigned trips, ETA, milestones, and document status.',
    'incidentSummary': 'Incident summary',
    'openChat': 'Open chat',
    'recentActivity': 'Recent Activity',
    'fuelLogs': 'Fuel Logs',
    'documentsUploaded': 'Documents Uploaded',
    'reportsSubmitted': 'Reports Submitted',
    'noActivity': 'No activity found yet.',
    'saveLanguage': 'Save Language',
    'languageUpdated': 'Language preference updated.',
    'branch': 'Branch',
    'emergencyContact': 'Emergency Contact',
    'license': 'License',
    'driver': 'Driver',
    'settings': 'Settings',
    'refresh': 'Refresh',
    'retry': 'Retry',
    'supportTitle': 'Support',
    'documentsTitle': 'Documents',
    'checkpointsTitle': 'Checkpoints',
    'issuesTitle': 'Issues',
    'transitPackTitle': 'Transit Pack',
    'name': 'Name',
    'company': 'Company',
    'contact': 'Contact',
    'kycStatus': 'KYC status',
    'partner': 'Partner',
    'customerAccount': 'Customer account',
    'notSet': 'Not set',
    'logout': 'Logout',
    'signOutCurrentSession': 'Sign out of the current mobile session',
    'driverProfileTitle': 'Driver profile',
    'customerProfileTitle': 'Customer profile',
    'emailAddress': 'Email address',
    'emailExample': 'example@email.com',
    'emailUsedForOtp': 'Email used for OTP',
    'phoneUsedForOtp': 'Phone used for OTP',
    'legalOrBusinessContactName': 'Your legal or business contact name',
    'optional': 'Optional',
    'cityOrBranch': 'City or branch',
    'driverPhoneHelp':
        'Use the registered driver phone number. Default demo login is +251900000015 with PIN 2112.',
    'driverPinLabel': '4-digit PIN',
    'driverPinHint': 'Enter your 4-digit PIN',
    'driverPinCreateHint': 'Create a 4-digit PIN',
    'driverFullNameHintText': 'Driver legal name',
    'driverPartnerCompanyHintText': 'External operator or fleet partner',
    'driverBranchHintText': 'Assigned branch or operations base',
    'driverEmergencyNameHintText': 'Required for field support',
    'driverLicenseHintText': 'Optional for now',
    'createDriverAccount': 'Create driver account',
    'continueToKyc': 'Continue to KYC',
    'driverAccess': 'Driver access',
    'savedDriverNumber': 'Saved driver number: {identifier}',
    'enterMinPassword': 'Enter a 4-digit PIN.',
    'pinDigitsOnly': 'PIN must contain numbers only.',
    'enterDriverFullName': 'Enter the driver full name.',
    'enterDriverBranch': 'Enter the assigned branch.',
    'enterPartnerCompany': 'Enter the partner company name.',
    'driverOnboardingTitle': 'Driver onboarding',
    'driverOnboardingSubtitle':
        'Use your phone number and create a 4-digit PIN, then complete the short driver profile before KYC upload.',
    'selectedPhone': 'Phone number: {identifier}',
    'driverSignupHelp':
        'Create a 4-digit PIN now. Next step: upload Fayda and driver license documents. Trip operations unlock only after KYC approval.',
    'internalDriverLabel': 'Internal driver',
    'externalDriverLabel': 'External driver',
    'driverKycTitle': 'Driver KYC',
    'kycSubmittedTitle': 'KYC Submitted',
    'kycUnderReviewTitle': 'KYC Under Review',
    'kycNeedsResubmissionTitle': 'KYC Needs Resubmission',
    'kycAccessRestrictedTitle': 'KYC Access Restricted',
    'kycPendingTitle': 'KYC Pending',
    'kycSubmittedSubtitle': 'Your KYC package is recorded and waiting for review.',
    'kycUnderReviewSubtitle':
        'Tikur Abay operations is reviewing your Fayda and license documents.',
    'kycRejectedSubtitle':
        'Update the missing or rejected documents to continue into trip operations.',
    'kycSuspendedSubtitle':
        'Your driver account is temporarily restricted. Contact support.',
    'kycPendingSubtitle': 'Complete onboarding before trip operations unlock.',
    'statusLabel': 'Status',
    'uploadedDocumentsTitle': 'Uploaded documents',
    'faydaFrontLabel': 'Fayda front',
    'faydaBackLabel': 'Fayda back',
    'driverLicenseLabel': 'Driver license',
    'uploadedStatus': 'Uploaded',
    'resubmitDocuments': 'Resubmit documents',
    'customerTripWorkspace': 'Customer trip workspace',
    'customerTripWorkspaceSubtitle':
        'Track assigned trips, ETA, payment state, and delivery documents in one place.',
    'tripQueue': 'Trip queue',
    'allTrips': 'All trips',
    'active': 'Active',
    'delayed': 'Delayed',
    'completed': 'Completed',
    'awaitingPod': 'Awaiting POD',
    'eta': 'ETA',
    'latestUpdate': 'Latest update',
    'invoiceStatus': 'Invoice status',
    'paymentStatus': 'Payment status',
    'route': 'Route',
    'status': 'Status',
    'customerName': 'Customer',
    'notAvailable': 'Not available',
    'timeNotRecorded': 'Time not recorded',
    'locationNotRecorded': 'Location not recorded',
    'systemUpdate': 'System update',
    'tripTimelineSubtitle':
        'Major milestones and checkpoint updates for this trip.',
    'tripDocumentsSubtitle':
        'Manifest, POD, receipts, and delivery files linked to this trip.',
    'tripPaymentSubtitle':
        'Invoice and payment follow-up linked to this shipment.',
    'mapTracking': 'Map tracking',
    'trackingSnapshot': 'Tracking snapshot',
    'trackingSnapshotSubtitle': 'Latest route progress and checkpoint context.',
    'noTimelineYet': 'No timeline updates recorded yet.',
    'noDocumentsYet': 'No linked documents are available yet.',
    'invoicePending': 'Invoice pending',
    'paymentPending': 'Payment pending',
    'driverTripWorkspace': 'Driver execution workspace',
    'driverTripWorkspaceSubtitle':
        'Assigned trips, route progress, and required field actions for today.',
    'currentAssignment': 'Current assignment',
    'tripInstructions': 'Trip instructions',
    'requiredUploads': 'Required uploads',
    'dispatchContact': 'Dispatch contact',
    'nextRequiredAction': 'Next required action',
    'arrivedAtLoading': 'Arrived at loading',
    'loadingCompleted': 'Loading completed',
    'borderUpdate': 'Border update',
    'delayUpdate': 'Delay update',
    'arrivedAtDestination': 'Arrived at destination',
    'offloadingCompleted': 'Offloading completed',
    'uploadPod': 'Upload POD',
    'reportIssue': 'Report issue',
    'tripChat': 'Trip chat',
    'tripDocuments': 'Trip documents',
    'reportType': 'Report type',
    'recentQueue': 'Recent queue',
    'openForm': 'Open form',
    'fuelReport': 'Fuel report',
    'accidentReport': 'Accident report',
    'tireIssue': 'Tire issue',
    'maintenanceNeeded': 'Maintenance needed',
    'roadObstacle': 'Road obstacle',
    'delayReport': 'Delay report',
    'breakdownReport': 'Breakdown report',
    'supportRequest': 'Support request',
    'checkpointUpdate': 'Checkpoint update',
    'borderCrossed': 'Border crossed',
    'podUploaded': 'POD uploaded',
    'operations': 'Operations',
    'maintenance': 'Maintenance',
    'workflow': 'Workflow',
    'fuel': 'Fuel',
    'incident': 'Incident',
    'draft': 'Draft',
    'submitted': 'Submitted',
    'underReview': 'Under review',
    'critical': 'Critical',
    'high': 'High',
    'medium': 'Medium',
    'low': 'Low',
    'stationName': 'Station name',
    'severity': 'Severity',
    'drivable': 'Drivable',
    'yes': 'Yes',
    'no': 'No',
    'injuries': 'Injuries',
    'policeReference': 'Police reference',
    'tirePosition': 'Tire position',
    'issueArea': 'Issue area',
    'obstacleType': 'Obstacle type',
    'expectedDelay': 'Expected delay',
    'delayType': 'Delay type',
    'checkpoint': 'Checkpoint',
    'breakdownType': 'Breakdown type',
    'towingNeeded': 'Towing needed',
    'saveDraft': 'Save draft',
    'fieldContext': 'Field context',
    'gpsLocation': 'GPS location',
    'autoCaptured': 'Auto captured',
    'submissionError': 'Submission failed. Review the fields and try again.',
    'loadFailed': 'Failed to load data.',
    'tryAgain': 'Try again',
    'customerHomeWorkspace': 'Customer home workspace',
    'customerHomeSubtitle':
        'Quotes, agreements, trips, and finance follow-up in one business view.',
    'pendingQuotes': 'Pending quotes',
    'pendingAgreements': 'Pending agreements',
    'unpaidInvoices': 'Unpaid invoices',
    'quickActions': 'Quick actions',
    'checkAvailability': 'Check availability',
    'uploadDocuments': 'Upload documents',
    'chatSupport': 'Chat support',
    'aiRecommendation': 'AI recommendation',
    'activityFeed': 'Activity feed',
    'noActiveBooking': 'No active booking right now.',
    'bookingStatus': 'Booking status',
    'requestedDate': 'Requested date',
    'cargo': 'Cargo',
    'openBookToRequestQuote':
        'Open Availability or Quotes to request transport and reserve fleet.',
    'pendingAssignment': 'Pending assignment',
    'activityDelayedTrip': 'Trip delayed',
    'activityAgreementSent': 'Agreement sent',
    'activityQuoteApproved': 'Quote approved',
    'activityInvoicePosted': 'Invoice posted',
    'driverAssignmentSubtitle':
        'Trip execution, route progress, field uploads, and dispatch follow-up for the active assignment.',
    'noAssignedTrip': 'No assigned trip right now.',
    'vehicle': 'Vehicle',
    'checkpointLabel': 'Checkpoint',
    'tripDetails': 'Trip details',
    'updateStatus': 'Update status',
    'docsPod': 'Docs / POD',
    'tripExecution': 'Trip execution',
    'tripExecutionSubtitle':
        'Use Reports for loading, offloading, delay, accident, breakdown, fuel, and obstacle actions.',
    'gpsTimeline': 'GPS and timeline',
    'gpsTimelineSubtitle':
        'Operations sees live movement and checkpoint updates from active trip sync.',
    'documentDiscipline': 'Document discipline',
    'documentDisciplineSubtitle':
        'Upload manifest, loading photos, offloading photos, and POD as the trip progresses.',
    'dispatcherNote': 'Dispatcher note',
    'keepCheckpointUpdatesCurrent':
        'Keep checkpoint updates and POD current during execution.',
    'freightRoute': 'Freight route',
    'inProgress': 'In progress',
    'uploaded': 'Uploaded',
    'availabilityWorkspace': 'Availability workspace',
    'availabilitySubtitle':
        'Search lanes, capacity, and vehicle fit before sending a quote or booking request.',
    'origin': 'Origin',
    'destination': 'Destination',
    'cargoType': 'Cargo type',
    'vehicleType': 'Vehicle type',
    'weight': 'Weight',
    'volume': 'Volume',
    'specialInstructions': 'Special instructions',
    'selectDate': 'Select date',
    'requestQuoteAction': 'Request quote',
    'reserveAction': 'Reserve',
    'bookingGuide': 'Booking guide',
    'bookingGuideQuote':
        'Use Request quote when pricing or vehicle fit still needs approval.',
    'bookingGuideReserve':
        'Use Reserve when the shipment is ready and operations can assign capacity.',
    'availabilityResults': 'Availability results',
    'estimatedPriceRange': 'Estimated price range',
    'transitExpectation': 'Transit expectation',
    'availableUnits': 'Available units',
    'lane': 'Lane',
    'quotesWorkspace': 'Quotes workspace',
    'quotesWorkspaceSubtitle':
        'Track requested, priced, approved, expired, and booked quotes in one place.',
    'requested': 'Requested',
    'priced': 'Priced',
    'approved': 'Approved',
    'expired': 'Expired',
    'booked': 'Booked',
    'validity': 'Validity',
    'estimatedAmount': 'Estimated amount',
    'bookNow': 'Book now',
    'quoteDetails': 'Quote details',
    'costBreakdown': 'Cost breakdown',
    'recommendedVehicle': 'Recommended vehicle',
    'requiredDocuments': 'Required documents',
    'noQuotesRightNow': 'No quotes are available right now.',
    'filterAll': 'All',
    'completeYourProfile': 'Complete Your Profile',
    'driverProfileDemoSubtitle':
        'Finish the basic driver details and continue to the next step. No file upload is required right now.',
    'demoDriverAutoFillInfo':
        'For demo flow, blank driver fields use placeholder values automatically so you can continue without filling everything.',
    'documentUploadSkippedInfo':
        'Document upload is skipped for now. You can continue immediately after saving this profile.',
    'continueAction': 'Continue',
    'driverDashboard': 'Driver Dashboard',
    'welcomeBack': 'Welcome back',
    'driverDemoLoadFailed':
        'Live trip data is not available right now. Demo guidance is shown so you can continue the presentation.',
    'driverDemoNoTrip':
        'No trip is assigned yet. Keep your profile and KYC readiness in good shape so dispatch can activate you quickly.',
    'profileKycPriority': 'Profile and KYC priority',
    'profileKycPrioritySubtitle':
        'Upload these first so approval and trip activation do not stall later.',
    'readyForDispatch': 'Ready for dispatch',
    'pendingReview': 'Pending review',
    'uploadFayda': 'Upload Fayda',
    'quickActionsTitle': 'Quick actions',
    'openDocuments': 'Open documents',
    'contactDispatch': 'Contact dispatch',
    'checkReports': 'Check reports',
    'driverAiRecommendation':
        'Upload Fayda front and back first, then driver license. That is the fastest path to approval and first trip assignment.',
    'todayTitle': 'Today',
    'accountAccessActive': 'Account access is active',
    'accountAccessActiveSubtitle':
        'OTP login worked. You can continue onboarding without waiting for a password setup.',
    'faydaStillMissing': 'Fayda is still missing',
    'faydaStillMissingSubtitle':
        'Add identity documents from Documents when you are ready to move from demo to approval flow.',
    'tripToolsUnlockAfterApproval': 'Trip tools will unlock after approval',
    'tripToolsUnlockAfterApprovalSubtitle':
        'Once KYC is approved, active trip, route timeline, and reporting actions will appear here.',
    'liveSyncStatus': 'Live sync status',
    'liveSyncStatusSubtitle':
        'Trip API data did not load, so this screen is showing demo fallback content instead of a hard error.',
    'driverTripsTitle': 'Driver trips',
    'driverTripsFallbackSubtitle':
        'Live trip data is unavailable right now. Demo trip guidance is shown instead so the driver workspace stays presentable.',
    'nextRecommendedAction': 'Next recommended action',
    'nextRecommendedActionSubtitle':
        'Keep Fayda and driver license ready, then return here after approval to start trip execution.',
    'assignedTripsRecentMovements':
        'Assigned trips, recent movements, and next required action.',
    'dispatchRoom': 'Dispatch',
    'dispatchRoomSubtitle':
        'Connect to dispatch for route, checkpoint, and assignment help.',
    'financeRoom': 'Finance',
    'financeRoomSubtitle':
        'Connect to finance for fuel, cash advance, and receipt follow-up.',
    'supportRoomSubtitle':
        'Connect to support for account, KYC, and app assistance.',
    'chatAssignmentHelp':
        'You can connect here for assignment updates, checkpoint instructions, and route clarifications.',
    'chatDriverAck':
        'Understood. I will use this room for trip coordination and document follow-up.',
    'chatSupportPrefill':
        'For demo mode, chat history is prefilled so the workspace remains presentable even before live conversations start.',
    'chatConnectSubtitle':
        'Connect here for dispatch, support, and operational updates.',
    'newMessagesSuffix': 'new',
    'sendMessageDispatchSupport': 'Send a message to dispatch or support',
    'messageCannotBeEmpty': 'Message cannot be empty.',
    'messageSent': 'Message sent.',
  },
  DriverLanguage.am: {
    'appTitle': 'የቲኩር አባይ ሞባይል',
    'customerHomeTitle': 'የደንበኛ መነሻ',
    'driverHomeTitle': 'የሹፌር መነሻ',
    'trip': 'ጉዞዎች',
    'report': 'ሪፖርቶች',
    'activity': 'እንቅስቃሴ',
    'chat': 'ቻት',
    'docs': 'ሰነዶች',
    'alerts': 'ማሳወቂያዎች',
    'profile': 'መገለጫ',
    'home': 'መነሻ',
    'availability': 'ተገኝነት',
    'quotes': 'ዋጋ ጥያቄዎች',
    'payments': 'ክፍያዎች',
    'notifications': 'ማሳወቂያዎች',
    'phoneOrEmail': 'ስልክ ወይም ኢሜይል',
    'password': 'የይለፍ ቃል',
    'language': 'ቋንቋ',
    'languageEnglish': 'እንግሊዝኛ',
    'languageAmharic': 'አማርኛ',
    'signIn': 'ግባ',
    'enterDriverConsole': 'የስራ ቦታን ክፈት',
    'signingIn': 'በመግባት ላይ...',
    'driverLoginIntro':
        'ጉዞዎችን፣ የመስክ ሪፖርቶችን፣ ሰነዶችን እና የዲስፓች ቻትን ከአንድ ሞባይል የስራ ቦታ ይድረሱ።',
    'mobileIntro': 'የደንበኛ እና የሹፌር ኦፕሬሽኖች በአንድ ደህንነቱ የተጠበቀ የሞባይል የስራ ቦታ።',
    'register': 'ይመዝገቡ',
    'createAccount': 'መለያ ፍጠር',
    'creatingAccount': 'መለያ በመፍጠር ላይ...',
    'fullName': 'ሙሉ ስም',
    'phoneNumber': 'ስልክ ቁጥር',
    'email': 'ኢሜይል',
    'roleSelection': 'ሚናዎን ይምረጡ',
    'customerBusinessUser': 'ደንበኛ / የንግድ ተጠቃሚ',
    'driverRole': 'ሹፌር',
    'welcomeTikurAbay': 'ወደ ጥቁር አባይ እንኳን በደህና መጡ',
    'welcomeMobileSubtitle': 'ለደንበኞች እና ለሹፌሮች ዘመናዊ የትራንስፖርት መግቢያ።',
    'continueAs': 'እንደ ማን ይቀጥሉ',
    'customerUserShort': 'ደንበኛ / ተጠቃሚ',
    'customerRoleSubtitle': 'በመጀመሪያ ስልክ ወይም ኢሜይል፣ ከዚያ OTP እና አጭር መረጃ ማጠናቀቅ።',
    'driverRoleSubtitle': 'ለቀላል የሹፌር መዳረሻ ስልክ ቁጥርዎን እና 4 አሃዝ PIN ይጠቀሙ።',
    'chooseHowContinue':
        'እንዴት መቀጠል እንደሚፈልጉ ይምረጡ። KYC እስኪፀድቅ ድረስ የሹፌር አገልግሎት ይገደባል።',
    'customerLoginTitle': 'የደንበኛ መግቢያ',
    'customerLoginSubtitle':
        'መጀመሪያ ስልክ ቁጥር ወይም ኢሜይል ያስገቡ። አንድ ጊዜ የሚጠቀሙትን ኮድ እንልካለን።',
    'driverLoginTitle': 'የሹፌር መግቢያ',
    'driverLoginSubtitle':
        'በስልክ ቁጥርዎ እና 4 አሃዝ PIN ይግቡ። KYC ፈቃድ አሁንም የጉዞ መዳረሻን ይቆጣጠራል።',
    'useEmailInstead': 'በምትኩ ኢሜይል ይጠቀሙ',
    'phoneDefaultSignIn': 'ስልክ አሁንም ዋናው የመግቢያ መንገድ ነው።',
    'sendOtp': 'OTP ላክ',
    'sendingCode': 'ኮድ በመላክ ላይ...',
    'phoneFirstAccess': 'ስልክ ቀዳሚ መግቢያ',
    'verifyCode': 'ኮዱን አረጋግጥ',
    'verifyingCode': 'በማረጋገጥ ላይ...',
    'resendCode': 'ኮዱን እንደገና ላክ',
    'resendingCode': 'በድጋሚ በመላክ ላይ...',
    'changeNumber': 'ቁጥሩን ቀይር',
    'otpCode': 'OTP ኮድ',
    'enterSixDigits': '6 ቁጥሮች ያስገቡ',
    'otpTitle': 'የማረጋገጫ ኮድ ያስገቡ',
    'driverType': 'የሹፌር አይነት',
    'internalDriver': 'የውስጥ ሹፌር',
    'externalDriver': 'የውጭ አጋር ሹፌር',
    'companyName': 'የኩባንያ ስም',
    'tradeLicense': 'የንግድ ፈቃድ',
    'tin': 'TIN',
    'vat': 'VAT',
    'address': 'አድራሻ',
    'faydaFront': 'የፋይዳ ፊት ሰነድ መለያ',
    'faydaBack': 'የፋይዳ ጀርባ ሰነድ መለያ',
    'selfieDocument': 'የራስ-ፎቶ ሰነድ መለያ',
    'driverLicense': 'የሹፌር ፈቃድ',
    'branchId': 'የቅርንጫፍ መለያ',
    'partnerCompany': 'የአጋር ኩባንያ',
    'partnerVehicleCode': 'የአጋር ተሽከርካሪ / ማፒንግ ኮድ',
    'emergencyContactName': 'የድንገተኛ ግንኙነት',
    'driverKycRequired': 'የሹፌር KYC ያስፈልጋል',
    'driverKycHelp':
        'የፋይዳ ፊትና ጀርባ፣ ስልክ እና የፈቃድ መረጃ ያስገቡ። የሹፌር እርምጃዎች ከHR ወይም ኦፕሬሽን ማጽደቅ በኋላ ይከፈታሉ።',
    'driverKycLifecycle': 'የKYC ዑደት',
    'driverKycLifecycleValue':
        'draft → submitted → under review → approved / rejected / suspended',
    'submitQuote': 'ዋጋ ጠይቅ',
    'sendBooking': 'ቡኪንግ ላክ',
    'availabilityAndQuotes': 'ተገኝነት እና ዋጋ ጥያቄዎች',
    'openWorkspace': 'የስራ ቦታን ክፈት',
    'forgotPassword': 'የይለፍ ቃል ረሳሁ',
    'support': 'ድጋፍ',
    'customer': 'ደንበኛ',
    'customerTrips': 'ጉዞዎች',
    'customerDocs': 'ሰነዶች',
    'myQuotes': 'ዋጋ ጥያቄዎች',
    'myTrips': 'ጉዞዎች',
    'driverTrips': 'ጉዞዎች',
    'reportCenter': 'ሪፖርት ማዕከል',
    'documentCenter': 'የሰነድ ማዕከል',
    'managerConsole': 'ማናጀር ኮንሶል',
    'pendingApproval': 'ማጽደቅን በመጠባበቅ ላይ',
    'trackShipment': 'ጭነትን ተከታተል',
    'quoteStatus': 'የዋጋ ጥያቄ ሁኔታ',
    'agreement': 'ስምምነት',
    'activeTrips': 'ንቁ ጉዞዎች',
    'invoicesDue': 'የሚከፈሉ ደረሰኞች',
    'currentBooking': 'የአሁኑ ቡኪንግ',
    'tripProgress': 'የጉዞ ሂደት',
    'supportShortcut': 'የድጋፍ አቋራጭ',
    'tripDetail': 'የጉዞ ዝርዝር',
    'milestones': 'ዋና እርምጃዎች',
    'currentStatus': 'የአሁኑ ሁኔታ',
    'latestCheckpoint': 'የቅርብ ጊዜ ቼክፖይንት',
    'assignedVehicle': 'የተመደበ ተሽከርካሪ',
    'podStatus': 'የPOD ሁኔታ',
    'viewDetail': 'ዝርዝርን ይመልከቱ',
    'noTripsYet':
        'እስካሁን ንቁ ጉዞዎች የሉም። ቡኪንግ ከተመደበ በኋላ የጉዞ ደረጃዎች እና ETA እዚህ ይታያሉ።',
    'noQuotesAvailable': 'አሁን ምንም የዋጋ ጥያቄዎች አይገኙም።',
    'reportOverview': 'የሪፖርት ማዕከል',
    'reportOverviewSubtitle':
        'ነዳጅ፣ ክስተቶች፣ መዘግየቶች፣ ጥገና እና የስራ ሂደት ማሻሻያዎች በአንድ የኦፕሬሽን ወረፋ።',
    'recentSubmissions': 'የቅርብ ጊዜ ልኮች',
    'noReportsYet': 'እስካሁን ምንም ሪፖርቶች አልተላኩም።',
    'nextAction': 'ቀጣይ እርምጃ',
    'fieldPackage': 'ጉዞ፣ ተሽከርካሪ፣ ሹፌር፣ GPS፣ ኦዶሜተር፣ አስቸኳይነት እና አባሪዎች',
    'fuelAndReceipts': 'ነዳጅ፣ ደረሰኝ፣ ማደያ እና ኦዶሜተር',
    'reportSubmittedSuccessfully': 'ልክ በትክክል ተመዝግቧል።',
    'descriptionRequired': 'መግለጫ ያስፈልጋል።',
    'odometerKm': 'ኦዶሜተር KM',
    'liters': 'ሊትሮች',
    'cost': 'ወጪ',
    'urgencyLabel': 'አስቸኳይነት',
    'notes': 'ማስታወሻዎች',
    'descriptionLabel': 'መግለጫ',
    'receiptAttachment': 'ደረሰኝ / አባሪ',
    'photoAttachment': 'የፎቶ አባሪ',
    'pick': 'ምረጥ',
    'submit': 'ላክ',
    'submitting': 'በመላክ ላይ...',
    'tripUnavailable': 'የጉዞ ዝርዝር አይገኝም።',
    'timeline': 'የጊዜ መስመር',
    'documents': 'ሰነዶች',
    'paymentLink': 'የክፍያ አገናኝ',
    'routeStatus': 'የመንገድ ሁኔታ',
    'customerWorkspace': 'የደንበኛ የስራ ቦታ',
    'assignedTripsAndDeliveryMilestones':
        'የተመደቡ ጉዞዎች፣ ETA፣ የማድረስ ደረጃዎች እና የሰነድ ሁኔታ።',
    'incidentSummary': 'የክስተት ማጠቃለያ',
    'openChat': 'ቻት ክፈት',
    'recentActivity': 'የቅርብ ጊዜ እንቅስቃሴ',
    'fuelLogs': 'የነዳጅ መዝገቦች',
    'documentsUploaded': 'የተጫኑ ሰነዶች',
    'reportsSubmitted': 'የተላኩ ሪፖርቶች',
    'noActivity': 'እስካሁን እንቅስቃሴ የለም።',
    'saveLanguage': 'ቋንቋን አስቀምጥ',
    'languageUpdated': 'የቋንቋ ምርጫ ተዘምኗል።',
    'branch': 'ቅርንጫፍ',
    'emergencyContact': 'የድንገተኛ ግንኙነት',
    'license': 'ፈቃድ',
    'driver': 'ሹፌር',
    'settings': 'ቅንብሮች',
    'refresh': 'አድስ',
    'retry': 'እንደገና ሞክር',
    'supportTitle': 'ድጋፍ',
    'documentsTitle': 'ሰነዶች',
    'checkpointsTitle': 'ቼክፖይንቶች',
    'issuesTitle': 'ችግኝቶች',
    'transitPackTitle': 'የትራንዚት ፓኬት',
    'name': 'ስም',
    'company': 'ኩባንያ',
    'contact': 'መገናኛ',
    'kycStatus': 'የKYC ሁኔታ',
    'partner': 'አጋር',
    'customerAccount': 'የደንበኛ መለያ',
    'notSet': 'አልተመዘገበም',
    'logout': 'ውጣ',
    'signOutCurrentSession': 'ከአሁኑ የሞባይል ክፍለ-ጊዜ ውጣ',
    'driverProfileTitle': 'የሹፌር መገለጫ',
    'customerProfileTitle': 'የደንበኛ መገለጫ',
    'emailAddress': 'የኢሜይል አድራሻ',
    'emailExample': 'example@email.com',
    'emailUsedForOtp': 'OTP የተላከበት ኢሜይል',
    'phoneUsedForOtp': 'OTP የተላከበት ስልክ',
    'legalOrBusinessContactName': 'ህጋዊ ወይም የንግድ መገናኛ ስምዎ',
    'optional': 'አማራጭ',
    'cityOrBranch': 'ከተማ ወይም ቅርንጫፍ',
    'driverPhoneHelp':
        'የተመዘገበውን የሹፌር ስልክ ቁጥር ይጠቀሙ። ነባሪ የሙከራ መግቢያ +251900000015 እና PIN 2112 ነው።',
    'driverPinLabel': '4 አሃዝ PIN',
    'driverPinHint': '4 አሃዝ PIN ያስገቡ',
    'driverPinCreateHint': '4 አሃዝ PIN ይፍጠሩ',
    'driverFullNameHintText': 'የሹፌሩ ህጋዊ ስም',
    'driverPartnerCompanyHintText': 'ውጫዊ ኦፕሬተር ወይም የፍሊት አጋር',
    'driverBranchHintText': 'የተመደበ ቅርንጫፍ ወይም የኦፕሬሽንስ መሠረት',
    'driverEmergencyNameHintText': 'ለመስክ ድጋፍ ያስፈልጋል',
    'driverLicenseHintText': 'ለአሁን አማራጭ ነው',
    'createDriverAccount': 'የሹፌር መለያ ፍጠር',
    'continueToKyc': 'ወደ KYC ቀጥል',
    'driverAccess': 'የሹፌር መዳረሻ',
    'savedDriverNumber': 'የተቀመጠ የሹፌር ቁጥር: {identifier}',
    'enterMinPassword': '4 አሃዝ PIN ያስገቡ።',
    'pinDigitsOnly': 'PIN ቁጥሮች ብቻ መያዝ አለበት።',
    'enterDriverFullName': 'የሹፌሩን ሙሉ ስም ያስገቡ።',
    'enterDriverBranch': 'የተመደበውን ቅርንጫፍ ያስገቡ።',
    'enterPartnerCompany': 'የአጋር ኩባንያውን ስም ያስገቡ።',
    'driverOnboardingTitle': 'የሹፌር ምዝገባ',
    'driverOnboardingSubtitle':
        'ስልክ ቁጥርዎን ተጠቅመው 4 አሃዝ PIN ይፍጠሩ፣ ከዚያም ከKYC አፕሎድ በፊት አጭር የሹፌር መረጃ ያጠናቅቁ።',
    'selectedPhone': 'ስልክ ቁጥር: {identifier}',
    'driverSignupHelp':
        '4 አሃዝ PIN አሁን ይፍጠሩ። ቀጣዩ እርምጃ: የፋይዳ እና የሹፌር ፈቃድ ሰነዶችን ይጫኑ። የጉዞ ኦፕሬሽኖች የሚከፈቱት KYC ከተፈቀደ በኋላ ብቻ ነው።',
    'internalDriverLabel': 'የውስጥ ሹፌር',
    'externalDriverLabel': 'የውጭ ሹፌር',
    'driverKycTitle': 'የሹፌር KYC',
    'kycSubmittedTitle': 'KYC ተልኳል',
    'kycUnderReviewTitle': 'KYC በግምገማ ላይ ነው',
    'kycNeedsResubmissionTitle': 'KYC እንደገና መላክ ይፈልጋል',
    'kycAccessRestrictedTitle': 'የKYC መዳረሻ ተገድቧል',
    'kycPendingTitle': 'KYC በመጠባበቅ ላይ ነው',
    'kycSubmittedSubtitle': 'የKYC ፓኬጅዎ ተመዝግቦ ለግምገማ በመጠባበቅ ላይ ነው።',
    'kycUnderReviewSubtitle':
        'ቲኩር አባይ ኦፕሬሽንስ የፋይዳ እና የፈቃድ ሰነዶችዎን በማየት ላይ ነው።',
    'kycRejectedSubtitle':
        'ወደ ጉዞ ኦፕሬሽን ለመቀጠል የጎደሉ ወይም የተከለከሉ ሰነዶችን ያዘምኑ።',
    'kycSuspendedSubtitle':
        'የሹፌር መለያዎ ለጊዜው ተገድቧል። ድጋፍን ያነጋግሩ።',
    'kycPendingSubtitle': 'የጉዞ ኦፕሬሽኖች ከመከፈታቸው በፊት ምዝገባውን ያጠናቅቁ።',
    'statusLabel': 'ሁኔታ',
    'uploadedDocumentsTitle': 'የተጫኑ ሰነዶች',
    'faydaFrontLabel': 'የፋይዳ ፊት',
    'faydaBackLabel': 'የፋይዳ ጀርባ',
    'driverLicenseLabel': 'የሹፌር ፈቃድ',
    'uploadedStatus': 'ተጭኗል',
    'resubmitDocuments': 'ሰነዶችን እንደገና ላክ',
    'customerTripWorkspace': 'የደንበኛ የጉዞ የስራ ቦታ',
    'customerTripWorkspaceSubtitle':
        'የተመደቡ ጉዞዎችን፣ ETA፣ የክፍያ ሁኔታን እና የማድረስ ሰነዶችን በአንድ ቦታ ይከታተሉ።',
    'tripQueue': 'የጉዞ ወረፋ',
    'allTrips': 'ሁሉም ጉዞዎች',
    'active': 'ንቁ',
    'delayed': 'ዘግይቷል',
    'completed': 'ተጠናቋል',
    'awaitingPod': 'POD በመጠባበቅ ላይ',
    'eta': 'ETA',
    'latestUpdate': 'የቅርብ ጊዜ ማሻሻያ',
    'invoiceStatus': 'የደረሰኝ ሁኔታ',
    'paymentStatus': 'የክፍያ ሁኔታ',
    'route': 'መንገድ',
    'status': 'ሁኔታ',
    'customerName': 'ደንበኛ',
    'notAvailable': 'አይገኝም',
    'timeNotRecorded': 'ሰዓት አልተመዘገበም',
    'locationNotRecorded': 'ቦታ አልተመዘገበም',
    'systemUpdate': 'የስርዓት ማሻሻያ',
    'tripTimelineSubtitle': 'ለዚህ ጉዞ ዋና ዋና ደረጃዎች እና የመቆጣጠሪያ ነጥብ ማሻሻያዎች።',
    'tripDocumentsSubtitle': 'ከዚህ ጉዞ ጋር የተያያዙ ማኒፌስት፣ POD፣ ደረሰኞች እና የማድረስ ፋይሎች።',
    'tripPaymentSubtitle': 'ከዚህ ጭነት ጋር የተያያዙ የደረሰኝ እና የክፍያ ክትትሎች።',
    'mapTracking': 'የካርታ ክትትል',
    'trackingSnapshot': 'የክትትል ማጠቃለያ',
    'trackingSnapshotSubtitle': 'የቅርብ ጊዜ የመንገድ ሂደት እና የመቆጣጠሪያ ነጥብ አውድ።',
    'noTimelineYet': 'እስካሁን የጊዜ መስመር ማሻሻያዎች አልተመዘገቡም።',
    'noDocumentsYet': 'እስካሁን የተያያዙ ሰነዶች የሉም።',
    'invoicePending': 'ደረሰኝ በመጠባበቅ ላይ',
    'paymentPending': 'ክፍያ በመጠባበቅ ላይ',
    'driverTripWorkspace': 'የሹፌር የአፈጻጸም የስራ ቦታ',
    'driverTripWorkspaceSubtitle': 'ለዛሬ የተመደቡ ጉዞዎች፣ የመንገድ ሂደት እና የመስክ እርምጃዎች።',
    'currentAssignment': 'የአሁኑ ምደባ',
    'tripInstructions': 'የጉዞ መመሪያዎች',
    'requiredUploads': 'የሚያስፈልጉ አፕሎዶች',
    'dispatchContact': 'የዲስፓች ግንኙነት',
    'nextRequiredAction': 'ቀጣይ የሚያስፈልግ እርምጃ',
    'arrivedAtLoading': 'ወደ ጭነት ቦታ ደርሷል',
    'loadingCompleted': 'ጭነት ተጠናቋል',
    'borderUpdate': 'የድንበር ማሻሻያ',
    'delayUpdate': 'የመዘግየት ማሻሻያ',
    'arrivedAtDestination': 'ወደ መዳረሻ ደርሷል',
    'offloadingCompleted': 'ማውረድ ተጠናቋል',
    'uploadPod': 'POD አፕሎድ አድርግ',
    'reportIssue': 'ችግር ሪፖርት አድርግ',
    'tripChat': 'የጉዞ ቻት',
    'tripDocuments': 'የጉዞ ሰነዶች',
    'reportType': 'የሪፖርት አይነት',
    'recentQueue': 'የቅርብ ጊዜ ወረፋ',
    'openForm': 'ፎርሙን ክፈት',
    'fuelReport': 'የነዳጅ ሪፖርት',
    'accidentReport': 'የአደጋ ሪፖርት',
    'tireIssue': 'የጎማ ችግር',
    'maintenanceNeeded': 'ጥገና ያስፈልጋል',
    'roadObstacle': 'የመንገድ እንቅፋት',
    'delayReport': 'የመዘግየት ሪፖርት',
    'breakdownReport': 'የመበላሸት ሪፖርት',
    'supportRequest': 'የድጋፍ ጥያቄ',
    'checkpointUpdate': 'የቼክፖይንት ማሻሻያ',
    'borderCrossed': 'ድንበር ተሻግሯል',
    'podUploaded': 'POD ተጫኗል',
    'operations': 'ኦፕሬሽን',
    'maintenance': 'ጥገና',
    'workflow': 'የስራ ሂደት',
    'fuel': 'ነዳጅ',
    'incident': 'ክስተት',
    'draft': 'ረቂቅ',
    'submitted': 'ተልኳል',
    'underReview': 'በግምገማ ላይ',
    'critical': 'ከፍተኛ አደጋ',
    'high': 'ከፍተኛ',
    'medium': 'መካከለኛ',
    'low': 'ዝቅተኛ',
    'stationName': 'የማደያ ስም',
    'severity': 'ክብደት',
    'drivable': 'ማንዳት ይቻላል',
    'yes': 'አዎ',
    'no': 'አይ',
    'injuries': 'ጉዳት',
    'policeReference': 'የፖሊስ ማጣቀሻ',
    'tirePosition': 'የጎማ ቦታ',
    'issueArea': 'የችግር ክፍል',
    'obstacleType': 'የእንቅፋት አይነት',
    'expectedDelay': 'የሚጠበቀው መዘግየት',
    'delayType': 'የመዘግየት አይነት',
    'checkpoint': 'ቼክፖይንት',
    'breakdownType': 'የመበላሸት አይነት',
    'towingNeeded': 'ቶዊንግ ያስፈልጋል',
    'saveDraft': 'ረቂቅ አስቀምጥ',
    'fieldContext': 'የመስክ አውድ',
    'gpsLocation': 'GPS ቦታ',
    'autoCaptured': 'በራስ-ሰር ተይዟል',
    'submissionError': 'ልኮች አልተሳኩም። መስኮቹን ይመርምሩ እና እንደገና ይሞክሩ።',
    'loadFailed': 'መረጃ መጫን አልተሳካም።',
    'tryAgain': 'እንደገና ሞክር',
    'customerHomeWorkspace': 'የደንበኛ የመነሻ የስራ ቦታ',
    'customerHomeSubtitle':
        'ዋጋ ጥያቄዎች፣ ስምምነቶች፣ ጉዞዎች እና የፋይናንስ ክትትል በአንድ የንግድ እይታ።',
    'pendingQuotes': 'በመጠባበቅ ላይ ያሉ ዋጋ ጥያቄዎች',
    'pendingAgreements': 'በመጠባበቅ ላይ ያሉ ስምምነቶች',
    'unpaidInvoices': 'ያልተከፈሉ ደረሰኞች',
    'quickActions': 'ፈጣን እርምጃዎች',
    'checkAvailability': 'ተገኝነትን ያረጋግጡ',
    'uploadDocuments': 'ሰነዶችን አፕሎድ ያድርጉ',
    'chatSupport': 'ከድጋፍ ጋር ቻት',
    'aiRecommendation': 'AI ምክር',
    'activityFeed': 'የእንቅስቃሴ ፊድ',
    'noActiveBooking': 'አሁን ንቁ ቡኪንግ የለም።',
    'bookingStatus': 'የቡኪንግ ሁኔታ',
    'requestedDate': 'የተጠየቀበት ቀን',
    'cargo': 'ጭነት',
    'openBookToRequestQuote':
        'የመጓጓዣ ጥያቄ ለመላክ እና መርከቦችን ለማስያዝ ተገኝነትን ወይም ዋጋ ጥያቄዎችን ይክፈቱ።',
    'pendingAssignment': 'ምደባን በመጠባበቅ ላይ',
    'activityDelayedTrip': 'ጉዞ ዘግይቷል',
    'activityAgreementSent': 'ስምምነት ተልኳል',
    'activityQuoteApproved': 'የዋጋ ጥያቄ ተፈቅዷል',
    'activityInvoicePosted': 'ደረሰኝ ተመዝግቧል',
    'driverAssignmentSubtitle':
        'ለንቁ ምደባው የጉዞ አፈጻጸም፣ የመንገድ ሂደት፣ የመስክ አፕሎዶች እና የዲስፓች ክትትል።',
    'noAssignedTrip': 'አሁን የተመደበ ጉዞ የለም።',
    'vehicle': 'ተሽከርካሪ',
    'checkpointLabel': 'ቼክፖይንት',
    'tripDetails': 'የጉዞ ዝርዝሮች',
    'updateStatus': 'ሁኔታ አዘምን',
    'docsPod': 'ሰነዶች / POD',
    'tripExecution': 'የጉዞ አፈጻጸም',
    'tripExecutionSubtitle':
        'ለመጫን፣ ለማውረድ፣ ለመዘግየት፣ ለአደጋ፣ ለመበላሸት፣ ለነዳጅ እና ለመንገድ እንቅፋት ሪፖርቶችን ይጠቀሙ።',
    'gpsTimeline': 'GPS እና የጊዜ መስመር',
    'gpsTimelineSubtitle':
        'ኦፕሬሽን ከንቁ ጉዞ ሲንክ የቀጥታ እንቅስቃሴን እና የቼክፖይንት ማሻሻያዎችን ያያል።',
    'documentDiscipline': 'የሰነድ ስርዓት',
    'documentDisciplineSubtitle':
        'ጉዞው ሲሄድ ማኒፌስት፣ የመጫኛ ፎቶዎች፣ የማውረጃ ፎቶዎች እና POD አፕሎድ ያድርጉ።',
    'dispatcherNote': 'የዲስፓች ማስታወሻ',
    'keepCheckpointUpdatesCurrent':
        'በአፈጻጸም ወቅት የቼክፖይንት ማሻሻያዎችን እና POD ወቅታዊ ያድርጉ።',
    'freightRoute': 'የጭነት መንገድ',
    'inProgress': 'በሂደት ላይ',
    'uploaded': 'ተጫኗል',
    'availabilityWorkspace': 'የተገኝነት የስራ ቦታ',
    'availabilitySubtitle':
        'ዋጋ ጥያቄ ወይም ቡኪንግ ከመላክዎ በፊት መስመሮችን፣ አቅምን እና የተሽከርካሪ ተስማሚነትን ይፈልጉ።',
    'origin': 'መነሻ',
    'destination': 'መዳረሻ',
    'cargoType': 'የጭነት አይነት',
    'vehicleType': 'የተሽከርካሪ አይነት',
    'weight': 'ክብደት',
    'volume': 'መጠን',
    'specialInstructions': 'ልዩ መመሪያዎች',
    'selectDate': 'ቀን ይምረጡ',
    'requestQuoteAction': 'ዋጋ ጠይቅ',
    'reserveAction': 'አስይዝ',
    'bookingGuide': 'የቡኪንግ መመሪያ',
    'bookingGuideQuote': 'ዋጋ ወይም የተሽከርካሪ ተስማሚነት አሁንም ማጽደቅ ሲፈልግ ዋጋ ጠይቅን ይጠቀሙ።',
    'bookingGuideReserve': 'ጭነቱ ዝግጁ ሲሆን እና ኦፕሬሽን አቅም ሊመድብ ሲችል አስይዝን ይጠቀሙ።',
    'availabilityResults': 'የተገኝነት ውጤቶች',
    'estimatedPriceRange': 'የሚገመት የዋጋ ክልል',
    'transitExpectation': 'የጉዞ ጊዜ ግምት',
    'availableUnits': 'የሚገኙ መኪናዎች',
    'lane': 'መስመር',
    'quotesWorkspace': 'የዋጋ ጥያቄ የስራ ቦታ',
    'quotesWorkspaceSubtitle':
        'የተጠየቁ፣ ዋጋ የተሰጣቸው፣ የተፈቀዱ፣ ያለፉ እና የተቡኩ ዋጋ ጥያቄዎችን በአንድ ቦታ ይከታተሉ።',
    'requested': 'ተጠይቋል',
    'priced': 'ዋጋ ተሰጥቷል',
    'approved': 'ተፈቅዷል',
    'expired': 'ጊዜው አልፏል',
    'booked': 'ተቡክቷል',
    'validity': 'የትክክለኛነት ጊዜ',
    'estimatedAmount': 'የሚገመት መጠን',
    'bookNow': 'አሁን ቡክ አድርግ',
    'quoteDetails': 'የዋጋ ጥያቄ ዝርዝር',
    'costBreakdown': 'የወጪ ማብራሪያ',
    'recommendedVehicle': 'የሚመከር ተሽከርካሪ',
    'requiredDocuments': 'የሚያስፈልጉ ሰነዶች',
    'noQuotesRightNow': 'አሁን ምንም የዋጋ ጥያቄዎች አይገኙም።',
    'filterAll': 'ሁሉም',
    'completeYourProfile': 'መገለጫዎን ያጠናቅቁ',
    'driverProfileDemoSubtitle':
        'መሠረታዊ የሹፌር መረጃዎችን ያጠናቅቁ እና ወደ ቀጣዩ ደረጃ ይቀጥሉ። አሁን የፋይል አፕሎድ አያስፈልግም።',
    'demoDriverAutoFillInfo':
        'ለዴሞ ፍሰት ባዶ የሹፌር መስኮች በራስ-ሰር በመሙላት ሳይሞሉ እንዲቀጥሉ ያደርጋሉ።',
    'documentUploadSkippedInfo':
        'የሰነድ አፕሎድ ለአሁኑ ተዘልሏል። ይህን መገለጫ ካስቀመጡ በኋላ ወዲያውኑ መቀጠል ይችላሉ።',
    'continueAction': 'ቀጥል',
    'driverDashboard': 'የሹፌር ዳሽቦርድ',
    'welcomeBack': 'እንኳን ደህና ተመለሱ',
    'driverDemoLoadFailed':
        'የቀጥታ የጉዞ መረጃ አሁን አይገኝም። ዴሞውን እንዲቀጥሉ የአስተዳደር መመሪያ ታይቷል።',
    'driverDemoNoTrip':
        'እስካሁን ምንም ጉዞ አልተመደበም። ዲስፓች በፍጥነት እንዲያንቀሳቅስዎ መገለጫዎን እና KYC ዝግጁነትዎን ያስተካክሉ።',
    'profileKycPriority': 'የመገለጫ እና KYC ቅድሚያ',
    'profileKycPrioritySubtitle':
        'ፈቃድ እና የጉዞ እንቅስቃሴ እንዳይዘገይ እነዚህን በመጀመሪያ ያቅርቡ።',
    'readyForDispatch': 'ለዲስፓች ዝግጁ',
    'pendingReview': 'በግምገማ ላይ',
    'uploadFayda': 'ፋይዳ አፕሎድ አድርግ',
    'quickActionsTitle': 'ፈጣን እርምጃዎች',
    'openDocuments': 'ሰነዶችን ክፈት',
    'contactDispatch': 'ዲስፓችን አግኝ',
    'checkReports': 'ሪፖርቶችን ይመልከቱ',
    'driverAiRecommendation':
        'በመጀመሪያ የፋይዳ ፊትና ጀርባ፣ ከዚያ የሹፌር ፈቃድ ያቅርቡ። ይህ ወደ ፈቃድ እና የመጀመሪያ ጉዞ ምደባ የሚወስድ ፈጣኑ መንገድ ነው።',
    'todayTitle': 'ዛሬ',
    'accountAccessActive': 'የመለያ መግቢያ ንቁ ነው',
    'accountAccessActiveSubtitle':
        'OTP መግቢያ ሰርቷል። ያለ የይለፍ ቃል ማቀናበር መጠበቅ ሳያስፈልግ ኦንቦርዲንግን መቀጠል ይችላሉ።',
    'faydaStillMissing': 'ፋይዳ ገና አልቀረበም',
    'faydaStillMissingSubtitle':
        'ከዴሞ ወደ ፈቃድ ፍሰት ለመሄድ ዝግጁ ሲሆኑ የመታወቂያ ሰነዶችን ከሰነዶች ክፍል ያክሉ።',
    'tripToolsUnlockAfterApproval': 'የጉዞ መሳሪያዎች ከፈቃድ በኋላ ይከፈታሉ',
    'tripToolsUnlockAfterApprovalSubtitle':
        'KYC ከተፈቀደ በኋላ ንቁ ጉዞ፣ የመንገድ የጊዜ መስመር እና የሪፖርት እርምጃዎች እዚህ ይታያሉ።',
    'liveSyncStatus': 'የቀጥታ ማመሳሰል ሁኔታ',
    'liveSyncStatusSubtitle':
        'የጉዞ API መረጃ አልተጫነም፣ ስለዚህ ይህ ስክሪን ከስህተት ይልቅ የዴሞ ይዘት እያሳየ ነው።',
    'driverTripsTitle': 'የሹፌር ጉዞዎች',
    'driverTripsFallbackSubtitle':
        'የቀጥታ የጉዞ መረጃ አይገኝም። የዴሞ የጉዞ መመሪያ ተሳይቷል ስለዚህ የሹፌር የስራ ቦታ የተዘጋጀ ይቆያል።',
    'nextRecommendedAction': 'ቀጣይ የሚመከር እርምጃ',
    'nextRecommendedActionSubtitle':
        'ፋይዳን እና የሹፌር ፈቃድን ዝግጁ ያድርጉ፣ ከዚያ ከፈቃድ በኋላ የጉዞ አፈጻጸም ለመጀመር ወደዚህ ይመለሱ።',
    'assignedTripsRecentMovements':
        'የተመደቡ ጉዞዎች፣ የቅርብ ጊዜ እንቅስቃሴዎች እና ቀጣይ የሚያስፈልግ እርምጃ።',
    'dispatchRoom': 'ዲስፓች',
    'dispatchRoomSubtitle': 'ለመንገድ፣ ለቼክፖይንት እና ለምደባ ድጋፍ ከዲስፓች ጋር ይገናኙ።',
    'financeRoom': 'ፋይናንስ',
    'financeRoomSubtitle': 'ለነዳጅ፣ ለገንዘብ ቅድሚያ እና ለደረሰኝ ክትትል ከፋይናንስ ጋር ይገናኙ።',
    'supportRoomSubtitle': 'ለመለያ፣ ለKYC እና ለመተግበሪያ እርዳታ ከድጋፍ ጋር ይገናኙ።',
    'chatAssignmentHelp':
        'ለምደባ ማሻሻያዎች፣ ለቼክፖይንት መመሪያዎች እና ለመንገድ ግልጽነት እዚህ መገናኘት ይችላሉ።',
    'chatDriverAck': 'ገብቶኛል። ይህን ክፍል ለጉዞ ቅንጅት እና ለሰነድ ክትትል እጠቀማለሁ።',
    'chatSupportPrefill':
        'ለዴሞ ሁኔታ የቻት ታሪክ አስቀድሞ ተሞልቷል ስለዚህ ከቀጥታ ውይይት በፊትም የስራ ቦታው ዝግጁ ይታያል።',
    'chatConnectSubtitle': 'ለዲስፓች፣ ለድጋፍ እና ለኦፕሬሽን ማሻሻያዎች እዚህ ይገናኙ።',
    'newMessagesSuffix': 'አዲስ',
    'sendMessageDispatchSupport': 'ለዲስፓች ወይም ለድጋፍ መልእክት ይላኩ',
    'messageCannotBeEmpty': 'መልእክት ባዶ ሊሆን አይችልም።',
    'messageSent': 'መልእክቱ ተልኳል።',
  },
};

String t(String key, {String? fallback}) {
  return _dictionary[driverLanguageNotifier.value]?[key] ?? fallback ?? key;
}

String tr(String key, {Map<String, String> params = const {}, String? fallback}) {
  var value = t(key, fallback: fallback);
  for (final entry in params.entries) {
    value = value.replaceAll('{${entry.key}}', entry.value);
  }
  return value;
}

String driverLanguageLabel(DriverLanguage language) {
  switch (language) {
    case DriverLanguage.am:
      return t('languageAmharic', fallback: 'Amharic');
    case DriverLanguage.en:
      return t('languageEnglish', fallback: 'English');
  }
}

Future<void> initializeDriverLanguage() async {
  final prefs = await SharedPreferences.getInstance();
  final stored = prefs.getString(_languageStorageKey);
  driverLanguageNotifier.value =
      stored == 'am' ? DriverLanguage.am : DriverLanguage.en;
}

Future<void> setDriverLanguage(DriverLanguage language,
    {bool persistRemote = true}) async {
  driverLanguageNotifier.value = language;
  final prefs = await SharedPreferences.getInstance();
  await prefs.setString(_languageStorageKey, language.name);
  if (persistRemote && DriverSession.accessToken != null) {
    try {
      await DriverApi.updateLanguagePreference(language.name);
    } catch (_) {
      // Keep local selection even if the API is temporarily unavailable.
    }
  }
}
