export const rbacMatrix = {
  super_admin: ['*'],
  executive_supervisor: [
    'dashboards:executive:view',
    'corridor:supplier:view',
    'corridor:djibouti:view',
    'corridor:dispatch:view',
    'corridor:yard:view',
    'corridor:finance:view',
    'corridor:shipment:override',
    'corridor:shipment:reassign',
    'customers:view',
    'payments:view',
    'notifications:view',
    'launch:view',
  ],
  supplier_agent: [
    'corridor:supplier:view',
    'corridor:shipment:assigned:view',
    'corridor:cargo:create',
    'corridor:cargo:update',
    'corridor:documents:origin:upload',
    'corridor:origin:stuffing:update',
    'corridor:origin:gatein:update',
  ],
  djibouti_release_agent: [
    'corridor:djibouti:view',
    'corridor:shipment:assigned:view',
    'corridor:release:update',
    'corridor:customs:update',
    'corridor:transit:update',
    'corridor:dispatch:handoff',
  ],
  djibouti_clearing_agent: [
    'corridor:djibouti:view',
    'corridor:shipment:assigned:view',
    'corridor:customs:update',
    'corridor:transit:update',
    'corridor:dispatch:handoff',
    'documents:view',
    'notifications:view',
  ],
  corridor_dispatch_agent: [
    'corridor:dispatch:view',
    'corridor:shipment:assigned:view',
    'corridor:trip:create',
    'corridor:trip:assign',
    'corridor:trip:update',
    'corridor:checkpoint:view',
    'corridor:checkpoint:update',
  ],
  dry_port_yard_agent: [
    'corridor:yard:view',
    'corridor:shipment:assigned:view',
    'corridor:arrival:update',
    'corridor:unload:update',
    'corridor:pod:update',
    'corridor:empty_return:update',
    'corridor:shipment:close',
  ],
  finance_customs_control: [
    'corridor:finance:view',
    'corridor:shipment:assigned:view',
    'corridor:finance:update',
    'corridor:customs:view',
    'corridor:documents:finance:upload',
    'payments:view',
    'invoices:view',
  ],
  customer_support_agent: [
    'dashboard:customer:view',
    'corridor:customer_summary:view',
    'chat:view',
    'chat:send',
    'notifications:view',
    'notifications:update',
  ],
  customer_user: [
    'dashboard:customer:view',
    'trips:own:view',
    'documents:own:view',
    'payments:own:view',
    'chat:own:view',
    'notifications:view',
    'notifications:update',
  ],
  customer_agent: [
    'dashboard:customer:view',
    'trips:own:view',
    'documents:own:view',
    'payments:own:view',
    'chat:own:view',
    'notifications:view',
    'notifications:update',
  ],
  internal_driver: [
    'mobile:login',
    'trips:view-assigned',
    'trips:update-status',
    'trip-events:view',
    'driver-reports:create',
    'chat:view',
    'chat:send',
    'documents:view',
    'documents:upload',
    'notifications:view',
    'notifications:update',
  ],
  external_driver: [
    'mobile:login',
    'trips:view-assigned',
    'trips:update-status',
    'trip-events:view',
    'driver-reports:create',
    'documents:view',
    'documents:upload',
    'notifications:view',
    'notifications:update',
  ],
  executive: [
    'dashboards:executive:view',
    'tracking:management:view',
    'performance:view',
    'maintenance:view',
    'finance:summary:view',
    'payments:view',
    'trips:view',
    'customers:view',
    'notifications:view',
    'launch:view',
  ],
  operations_manager: [
    'trips:view',
    'dispatch:view',
    'tracking:management:view',
    'driver-reports:view',
    'chat:view',
    'drivers:view',
    'vehicles:maintenance:view',
    'documents:view',
    'notifications:view',
    'notifications:update',
    'launch:view',
    'launch:update',
  ],
  dispatcher: [
    'trips:view',
    'dispatch:view',
    'driver-reports:view',
    'chat:view',
    'drivers:view',
    'documents:view',
    'notifications:view',
    'notifications:update',
    'launch:view',
  ],
  technical_manager: [
    'maintenance:view',
    'repair-orders:view',
    'spare-parts:view',
    'vehicles:maintenance:view',
    'notifications:view',
    'launch:view',
  ],
  marketing_officer: [
    'customers:view',
    'quotes:view',
    'agreements:view',
    'vehicles:availability:view',
    'notifications:view',
    'launch:view',
  ],
  finance_officer: [
    'payments:view',
    'invoices:view',
    'finance:summary:view',
    'notifications:view',
    'launch:view',
  ],
  hr_officer: [
    'drivers:view',
    'employees:view',
    'performance:view',
    'notifications:view',
    'launch:view',
  ],
  driver: [
    'mobile:login',
    'trips:view-assigned',
    'trips:update-status',
    'trip-events:view',
    'driver-reports:create',
    'driver-reports:view',
    'chat:view',
    'chat:send',
    'documents:view',
    'documents:upload',
    'notifications:view',
    'notifications:update',
  ],
  customer: [
    'dashboard:customer:view',
    'trips:own:view',
    'agreements:own:view',
    'documents:own:view',
    'documents:upload',
    'payments:own:view',
    'chat:own:view',
    'notifications:view',
    'notifications:update',
  ],
};
