export const routeCatalog = {
  auth: [
    'POST /auth/register',
    'POST /auth/login',
    'POST /auth/logout',
    'POST /auth/refresh-token',
    'GET /auth/me',
    'POST /auth/change-password',
    'POST /auth/forgot-password',
    'POST /auth/reset-password',
  ],
  roles: ['GET /roles', 'POST /roles', 'GET /roles/:id', 'PATCH /roles/:id', 'DELETE /roles/:id'],
  users: [
    'GET /users',
    'POST /users',
    'GET /users/:id',
    'PATCH /users/:id',
    'PATCH /users/:id/status',
    'DELETE /users/:id',
  ],
  branches: ['GET /branches', 'POST /branches', 'GET /branches/:id', 'PATCH /branches/:id', 'DELETE /branches/:id'],
  employees: [
    'GET /employees',
    'POST /employees',
    'GET /employees/:id',
    'PATCH /employees/:id',
    'PATCH /employees/:id/status',
    'GET /employees/:id/documents',
    'GET /employees/:id/performance',
    'GET /employees/:id/salaries',
  ],
  drivers: [
    'GET /drivers',
    'POST /drivers',
    'GET /drivers/:id',
    'PATCH /drivers/:id',
    'PATCH /drivers/:id/status',
    'GET /drivers/:id/trips',
    'GET /drivers/:id/performance',
    'GET /drivers/:id/documents',
    'GET /drivers/:id/license-alerts',
  ],
  customers: [
    'GET /customers',
    'POST /customers',
    'GET /customers/:id',
    'PATCH /customers/:id',
    'PATCH /customers/:id/status',
    'GET /customers/:id/agreements',
    'GET /customers/:id/quotes',
    'GET /customers/:id/trips',
    'GET /customers/:id/invoices',
    'GET /customers/:id/documents',
  ],
  vehicles: [
    'GET /vehicles',
    'POST /vehicles',
    'GET /vehicles/:id',
    'PATCH /vehicles/:id',
    'PATCH /vehicles/:id/status',
    'GET /vehicles/:id/gps',
    'GET /vehicles/:id/trips',
    'GET /vehicles/:id/maintenance-plans',
    'GET /vehicles/:id/maintenance-records',
    'GET /vehicles/:id/documents',
    'GET /vehicles/:id/location-history',
    'POST /vehicles/:id/assign-branch',
  ],
  trailers: ['GET /trailers', 'POST /trailers', 'GET /trailers/:id', 'PATCH /trailers/:id', 'PATCH /trailers/:id/status'],
  trips: [
    'GET /trips',
    'POST /trips',
    'GET /trips/:id',
    'PATCH /trips/:id',
    'PATCH /trips/:id/status',
    'POST /trips/:id/assign-driver',
    'POST /trips/:id/assign-vehicle',
    'POST /trips/:id/start',
    'POST /trips/:id/load',
    'POST /trips/:id/offload',
    'POST /trips/:id/mark-delivered',
    'POST /trips/:id/complete',
    'POST /trips/:id/report-delay',
    'POST /trips/:id/report-breakdown',
    'GET /trips/:id/events',
    'POST /trips/:id/events',
    'GET /trips/:id/documents',
    'GET /trips/:id/chat-room',
    'GET /trips/:id/route-history',
    'GET /trips/:id/proof-of-delivery',
  ],
  tracking: [
    'POST /tracking/gps-points',
    'GET /tracking/live-map',
    'GET /tracking/vehicles/:vehicleId/live',
    'GET /tracking/vehicles/offline',
    'GET /tracking/trips/:tripId/live',
    'GET /tracking/trips/:tripId/history',
    'GET /tracking/alerts',
  ],
  operations: [
    'GET /operations/fleet-summary',
    'GET /operations/available-vehicles',
    'GET /operations/unavailable-vehicles',
    'GET /operations/fuel-logs',
    'GET /operations/maintenance-due',
    'GET /operations/tire-due',
    'GET /operations/parts-history',
    'GET /operations/vehicle-status-board',
    'GET /operations/rental-partners/performance',
    'GET /operations/rental-partners/recommended',
    'POST /operations/fuel-logs',
    'POST /operations/vehicle-service-history',
    'POST /operations/part-replacements',
  ],
  maintenancePlans: [
    'GET /maintenance-plans',
    'POST /maintenance-plans',
    'GET /maintenance-plans/:id',
    'PATCH /maintenance-plans/:id',
    'DELETE /maintenance-plans/:id',
    'GET /maintenance-plans/due-soon',
    'GET /maintenance-plans/overdue',
  ],
  maintenanceDashboard: [
    'GET /maintenance/alerts',
    'GET /maintenance/due-vehicles',
    'GET /maintenance/tire-inspection-due',
    'GET /maintenance/overdue',
    'GET /maintenance/rules',
  ],
  maintenanceRecords: [
    'GET /maintenance-records',
    'POST /maintenance-records',
    'GET /maintenance-records/:id',
    'PATCH /maintenance-records/:id',
    'GET /maintenance-records/:id/documents',
  ],
  spareParts: [
    'GET /spare-parts',
    'POST /spare-parts',
    'GET /spare-parts/:id',
    'PATCH /spare-parts/:id',
    'PATCH /spare-parts/:id/stock',
    'GET /spare-parts/low-stock',
    'GET /spare-parts/:id/usage-history',
  ],
  repairOrders: [
    'GET /repair-orders',
    'POST /repair-orders',
    'GET /repair-orders/:id',
    'PATCH /repair-orders/:id',
    'PATCH /repair-orders/:id/status',
    'POST /repair-orders/:id/close',
  ],
  quotes: [
    'GET /quotes',
    'POST /quotes',
    'GET /quotes/:id',
    'PATCH /quotes/:id',
    'PATCH /quotes/:id/status',
    'POST /quotes/:id/convert-to-agreement',
    'POST /quotes/:id/convert-to-trip',
  ],
  agreements: [
    'GET /agreements',
    'GET /agreements/my',
    'POST /agreements',
    'GET /agreements/:id',
    'PATCH /agreements/:id',
    'PATCH /agreements/:id/status',
    'POST /agreements/:id/send-to-customer',
    'POST /agreements/:id/approve',
    'POST /agreements/:id/send-sign-link',
    'POST /agreements/:id/sign',
    'GET /agreements/:id/download',
    'POST /agreements/:id/renew',
    'GET /agreements/:id/versions',
    'GET /agreements/:id/document',
    'GET /agreements/expiring-soon',
  ],
  invoices: [
    'GET /invoices',
    'POST /invoices',
    'GET /invoices/:id',
    'PATCH /invoices/:id',
    'PATCH /invoices/:id/status',
    'POST /invoices/:id/send',
    'GET /invoices/overdue',
    'GET /invoices/:id/payments',
  ],
  payments: [
    'GET /payments',
    'GET /payments/workspace',
    'GET /payments/my',
    'GET /payments/communications/history',
    'GET /payments/:paymentId/communications',
    'POST /payments/communications/reminder',
    'POST /payments/communications/thank-you',
    'POST /payments/communications/receipt',
    'POST /payments/pay',
    'POST /payments',
    'GET /payments/:id',
    'PATCH /payments/:id',
    'PATCH /payments/:id/status',
    'GET /payments/customer-receipts',
    'GET /payments/salary-payments',
    'GET /payments/commission-payments',
  ],
  communications: [
    'POST /communications/send',
    'GET /communications/history',
    'GET /communications/templates',
    'POST /communications/preview',
  ],
  corridor: [
    'GET /corridor/access-matrix',
    'GET /corridor/shipments',
    'GET /corridor/shipments/:shipmentRef',
    'GET /corridor/customer-portal',
    'GET /corridor/workspaces/:workspace',
    'GET /corridor/driver/transit-pack',
    'POST /corridor/shipments/:shipmentRef/clearance/documents-ready',
    'POST /corridor/shipments/:shipmentRef/clearance/acknowledge',
    'POST /corridor/shipments/:shipmentRef/clearance/request-missing-docs',
    'POST /corridor/shipments/:shipmentRef/clearance/start',
    'POST /corridor/shipments/:shipmentRef/clearance/complete',
    'POST /corridor/shipments/:shipmentRef/clearance-pack',
    'POST /corridor/shipments/:shipmentRef/documents/bulk-download',
    'POST /corridor/shipments/:shipmentRef/documents/:shipmentDocumentId/access-log',
    'GET /corridor/shipments/:shipmentRef/document-access-log',
  ],
  drivingSchool: [
    'GET /driving-school/dashboard',
  ],
  salaries: [
    'GET /salaries',
    'POST /salaries',
    'GET /salaries/:id',
    'PATCH /salaries/:id',
    'POST /salaries/:id/process',
    'POST /salaries/:id/mark-paid',
  ],
  commissions: [
    'GET /commissions',
    'POST /commissions',
    'GET /commissions/:id',
    'PATCH /commissions/:id',
    'POST /commissions/:id/approve',
    'POST /commissions/:id/mark-paid',
  ],
  documents: [
    'GET /documents',
    'GET /documents/policy',
    'POST /documents/upload',
    'POST /documents/upload-url',
    'POST /documents/finalize-upload',
    'GET /documents/:id',
    'GET /documents/:id/download',
    'GET /documents/:id/download/file',
    'GET /documents/:id/download/resolve',
    'PATCH /documents/:id',
    'PATCH /documents/:id/approve',
    'PATCH /documents/:id/reject',
    'DELETE /documents/:id',
    'GET /documents/expiring-soon',
    'GET /documents/by-entity/:entityType/:entityId',
  ],
  commercial: [
    'GET /commercial/workspace',
    'GET /leads',
    'POST /leads',
    'GET /available-vehicles',
    'GET /onboarding-tasks',
    'POST /onboarding-tasks',
    'GET /outbound-notifications',
    'POST /outbound-notifications',
  ],
  chat: [
    'GET /chat/rooms',
    'POST /chat/rooms',
    'GET /chat/rooms/:id',
    'PATCH /chat/rooms/:id',
    'GET /chat/rooms/:id/messages',
    'POST /chat/rooms/:id/messages',
    'PATCH /chat/messages/:id/seen',
    'POST /chat/rooms/:id/participants',
  ],
  notifications: [
    'GET /notifications',
    'PATCH /notifications/:id/read',
    'PATCH /notifications/read-all',
    'GET /notifications/unread-count',
  ],
  driverReports: [
    'POST /driver-reports',
    'GET /driver-reports',
    'GET /driver-reports/:id',
    'PATCH /driver-reports/:id/status',
  ],
  mobile: [
    'POST /driver-kyc',
    'GET /driver-kyc/:id',
    'PATCH /driver-kyc/:id/status',
    'POST /bookings',
    'GET /bookings/my',
    'GET /fleet/available',
    'POST /quotes/request',
    'GET /quotes/my',
    'POST /fuel-logs',
    'POST /availability-reports',
    'POST /leave-requests',
    'GET /activity/my',
  ],
  maintenanceNotifications: [
    'POST /maintenance-notifications',
    'GET /maintenance-notifications',
    'PATCH /maintenance-notifications/:id/read',
  ],
  performance: [
    'GET /performance/employees/summary',
    'GET /performance/employees',
    'GET /performance/employees/:id',
    'GET /performance/employees/:id/activity',
    'GET /performance/employees/:id/customers',
    'GET /performance/employees/:id/loads',
    'GET /performance/drivers/summary',
    'GET /performance/drivers',
    'GET /performance/drivers/:id',
    'GET /performance/drivers/:id/trips',
    'GET /performance/drivers/:id/customers',
    'GET /performance/drivers/:id/incidents',
    'POST /performance-reviews',
    'GET /performance-reviews/:id',
    'PATCH /performance-reviews/:id',
  ],
  dashboards: [
    'GET /dashboards/operations/summary',
    'GET /dashboards/operations/live-fleet',
    'GET /dashboards/operations/delayed-trips',
    'GET /dashboards/operations/djibouti-trips',
    'GET /dashboards/technical/summary',
    'GET /dashboards/technical/maintenance-due',
    'GET /dashboards/technical/low-stock-parts',
    'GET /dashboards/marketing/summary',
    'GET /dashboards/marketing/available-vehicles',
    'GET /dashboards/marketing/pipeline',
    'GET /dashboards/finance/summary',
    'GET /dashboards/finance/outstanding-invoices',
    'GET /dashboards/finance/revenue-by-route',
    'GET /dashboards/finance/profit-by-vehicle',
    'GET /dashboards/management/executive-summary',
    'GET /dashboards/management/ai-command-center',
    'GET /dashboards/management/executive-workspace',
    'GET /dashboards/management/fleet-utilization',
    'GET /dashboards/management/driver-performance',
    'GET /dashboards/management/branch-performance',
    'GET /dashboard/ai-command-center',
    'GET /dashboard/executive-workspace',
  ],
  auditLogs: ['GET /audit-logs', 'GET /audit-logs/:entityType/:entityId'],
};
